version: '2'
services:
    luckycoin-app:
        image: luckycoin
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://luckycoin-mysql:3306/luckycoin?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=luckycoin-elasticsearch:9300
        ports:
            - 8080:8080
    luckycoin-mysql:
        extends:
            file: mysql.yml
            service: luckycoin-mysql
    luckycoin-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: luckycoin-elasticsearch
