package com.pep.luckycoin.domain.enumeration;

/**
 * The Location enumeration.
 */
public enum Location {
    BUCURESTI, ALBA, ARAD, ARGES, BACAU, BIHOR, BISTRITA_NASAUD, BOTOSANI, BRASOV, BRAILA, BUZAU, CARAS_SEVERIN, CALARASI, CLUJ, CONSTANTA, COVASNA, DAMBOVITA, DOLJ, GALATI, GIURGIU, GORJ, HARGHITA, HUNEDOARA, IALOMITA, IASI, ILFOV, MARAMURES, MEHEDINTI, MURES, NEAMT, OLT, PRAHOVA, SATU_MARE, SALAJ, SIBIU, SUCEAVA, TELEORMAN, TIMIS, TULCEA, VALCEA, VASLUI, VRANCEA
}
